"""add_provider_integrations_and_test_history

Revision ID: 7f87b241f1d3
Revises: f497a4bc3ef8
Create Date: 2026-09-29 07:36:27.240062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f87b241f1d3'
down_revision: Union[str, Sequence[str], None] = 'f497a4bc3ef8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_integrations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider_name', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('encrypted_credentials', sa.Text(), nullable=False),
    sa.Column('base_url', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_tested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_integrations_provider_name'), 'provider_integrations', ['provider_name'], unique=False)
    op.create_index(op.f('ix_provider_integrations_user_id'), 'provider_integrations', ['user_id'], unique=False)
    op.create_table('api_test_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=True),
    sa.Column('service_id', sa.UUID(), nullable=True),
    sa.Column('provider_name', sa.String(length=50), nullable=False),
    sa.Column('operation', sa.String(length=100), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('response_time_ms', sa.Float(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['provider_integrations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['service_id'], ['api_services.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_test_history_created_at'), 'api_test_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_api_test_history_provider_id'), 'api_test_history', ['provider_id'], unique=False)
    op.create_index(op.f('ix_api_test_history_service_id'), 'api_test_history', ['service_id'], unique=False)
    op.add_column('api_services', sa.Column('provider_id', sa.UUID(), nullable=True))
    op.add_column('api_services', sa.Column('config', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_api_services_provider_id'), 'api_services', ['provider_id'], unique=False)
    op.create_foreign_key('fk_api_services_provider_id', 'api_services', 'provider_integrations', ['provider_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_api_services_provider_id', 'api_services', type_='foreignkey')
    op.drop_index(op.f('ix_api_services_provider_id'), table_name='api_services')
    op.drop_column('api_services', 'config')
    op.drop_column('api_services', 'provider_id')
    op.drop_index(op.f('ix_api_test_history_service_id'), table_name='api_test_history')
    op.drop_index(op.f('ix_api_test_history_provider_id'), table_name='api_test_history')
    op.drop_index(op.f('ix_api_test_history_created_at'), table_name='api_test_history')
    op.drop_table('api_test_history')
    op.drop_index(op.f('ix_provider_integrations_user_id'), table_name='provider_integrations')
    op.drop_index(op.f('ix_provider_integrations_provider_name'), table_name='provider_integrations')
    op.drop_table('provider_integrations')
    # ### end Alembic commands ###
